-- MySQL Script generated by MySQL Workbench
-- Thu Jul 28 21:08:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Servistory
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `Servistory` ;

-- -----------------------------------------------------
-- Schema Servistory
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Servistory` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table `Servistory`.`Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servistory`.`Vendor` ;

CREATE TABLE IF NOT EXISTS `Servistory`.`Vendor` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NULL,
  `timezone` VARCHAR(50) NOT NULL DEFAULT 'Australia/Canberra',
  `email` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NOT NULL,
  `date_time_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_time_updated` DATETIME NULL,
  `contact_no` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Servistory`.`Work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servistory`.`Work` ;

CREATE TABLE IF NOT EXISTS `Servistory`.`Work` (
  `id` VARCHAR(50) NOT NULL,
  `customer_name` VARCHAR(50) NOT NULL,
  `customer_phone` VARCHAR(20) NOT NULL,
  `vendor_id` VARCHAR(50) NOT NULL,
  `tracking_no` VARCHAR(20) NULL,
  `car_model` VARCHAR(100) NULL,
  `plate_no` VARCHAR(20) NULL,
  `note` TEXT NULL,
  `status` ENUM('PENDING', 'IN_WORKSHOP', 'WORK_COMMENCED', 'AWAITING_PARTS', 'COMPLETED', 'COLLECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `date_time_arrived` DATETIME NULL,
  `date_time_pickup` DATETIME NULL,
  `date_time_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_time_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `vendor_id`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `Servistory`.`Vendor` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `vendor_id_idx` ON `Servistory`.`Work` (`vendor_id` ASC);

CREATE INDEX `status_idx` ON `Servistory`.`Work` (`status` ASC);

CREATE INDEX `customer_name_idx` ON `Servistory`.`Work` (`customer_name` ASC);

CREATE INDEX `customer_phone_idx` ON `Servistory`.`Work` (`customer_phone` ASC);

CREATE INDEX `plate_no_idx` ON `Servistory`.`Work` (`plate_no` ASC);


-- -----------------------------------------------------
-- Table `Servistory`.`WorkRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servistory`.`WorkRequest` ;

CREATE TABLE IF NOT EXISTS `Servistory`.`WorkRequest` (
  `id` VARCHAR(50) NOT NULL,
  `work_id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `reason` TEXT NULL,
  `attachments` TEXT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `date_time_completed` DATETIME NOT NULL,
  `status` ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `tracking_no` VARCHAR(20) NULL,
  `date_time_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_time_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `work_id`
    FOREIGN KEY (`work_id`)
    REFERENCES `Servistory`.`Work` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `work_id_idx` ON `Servistory`.`WorkRequest` (`work_id` ASC);

CREATE INDEX `status_idx` ON `Servistory`.`WorkRequest` (`status` ASC);
