 
const DATE_PICKER_FORMAT = "yyyy-MM-dd";
const TIME_PICKER_FORMAT = "HH:mm";
const DATE_TIME_PICKER_FORMAT = "yyyy-MM-dd HH:mm";

const DATE_DISPLAY_FORMAT = "dd MMM yyyy";

const WORKS_PER_PAGE = 10;

const STATUS_TO_TEXT_MAPPER = {
    'PENDING': 'AWAITING VEHICLE',
    'IN_WORKSHOP': 'VEHICLE IN WORKSHOP',
    'WORK_COMMENCED': 'WORK COMMENCED',
    'AWAITING_PARTS': 'AWAITING PARTS',
    'COMPLETED': 'READY TO PICKUP',
    'COLLECTED': 'COLLECTED',
    'CANCELLED': 'CANCELLED'
};

export { 
    DATE_PICKER_FORMAT,
    TIME_PICKER_FORMAT,
    DATE_TIME_PICKER_FORMAT,
    DATE_DISPLAY_FORMAT,
    WORKS_PER_PAGE,
    STATUS_TO_TEXT_MAPPER
};